version: '3'

services: 
  docker-mysql:
    image: mysql:latest
    container_name: docker-mysql
    volumes:
    - /my/own/datadir:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notes_app
      - MYSQL_PASSWORD=root
  spring-boot-easynotes-app:
    build:
      context: .
      dockerfile: Dockerfile-notesmicroservice
    image: easynotes
    container_name: easynotes_app
    depends_on:
      - docker-mysql
    ports:
      - 9696:9696
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=notes_app
      - DATABASE_PORT=3306